# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126GvxKaYYSCfRFWvHgB9vVjTca_Uf5TS
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title of the app
st.title("Firearm Injury Death Data Visualization")

# Load the CSV file

data = pd.read_csv("Firearm Injury Death by Year, New Mexico and U.S.csv")

st.write("### Data Preview")
st.dataframe(data)

# Column Selection for Visualization
columns = [
    "Year",
    "Deaths per 100,000 Population, Age-adjusted",
    "95% Confidence Interval, Lower Limit",
    "95% Confidence Interval, Upper Limit",
    "Count",
    "Population Count Estimate",
]

x_column = st.selectbox("Select X-axis column", columns)
y_column = st.selectbox("Select Y-axis column", columns)

# Dropdown for graph type
graph_type = st.selectbox(
    "Select Graph Type",
    ["Line", "Scatter", "Bar"],
)

# Plot button
if st.button("Plot Graph"):
    fig, ax = plt.subplots()

    # Convert Year to numeric if selected
    if x_column == "Year":
        data[x_column] = pd.to_numeric(data[x_column], errors='coerce')

    if graph_type == "Line":
        ax.plot(data[x_column], data[y_column], marker='o')
        ax.set_title(f"{y_column} vs {x_column} (Line Plot)")

    elif graph_type == "Scatter":
        ax.scatter(data[x_column], data[y_column])
        ax.set_title(f"{y_column} vs {x_column} (Scatter Plot)")

    elif graph_type == "Bar":
        ax.bar(data[x_column], data[y_column])
        ax.set_title(f"{y_column} vs {x_column} (Bar Chart)")

    # Labels
    ax.set_xlabel(x_column)
    ax.set_ylabel(y_column)
    st.pyplot(fig)

st.write("Tip: Ensure the selected columns have appropriate data for visualization.")

